## This file is a general .xdc for the Nexys A7-100T
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project
## Note: As the Nexys 4 DDR was rebranded to the Nexys A7 with no substantial changes, this XDC file will also work for the Nexys 4 DDR.

## Clock signal
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports CLK100MHZ]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK100MHZ]


##Switches
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {SW[0]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {SW[1]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {SW[2]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {SW[3]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {SW[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {SW[5]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {SW[6]}]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {SW[7]}]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS18} [get_ports {SW[8]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS18} [get_ports {SW[9]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {SW[10]}]
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {SW[11]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {SW[12]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {SW[13]}]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports {SW[14]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {SW[15]}]

## LEDs
# set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { LED[0] }]; #IO_L18P_T2_A24_15 Sch=led[0]
# set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { LED[1] }]; #IO_L24P_T3_RS1_15 Sch=led[1]
# set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { LED[2] }]; #IO_L17N_T2_A25_15 Sch=led[2]
# set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { LED[3] }]; #IO_L8P_T1_D11_14 Sch=led[3]
# set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { LED[4] }]; #IO_L7P_T1_D09_14 Sch=led[4]
# set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports { LED[5] }]; #IO_L18N_T2_A11_D27_14 Sch=led[5]
# set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { LED[6] }]; #IO_L17P_T2_A14_D30_14 Sch=led[6]
# set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { LED[7] }]; #IO_L18P_T2_A12_D28_14 Sch=led[7]
# set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { LED[8] }]; #IO_L16N_T2_A15_D31_14 Sch=led[8]
# set_property -dict { PACKAGE_PIN T15   IOSTANDARD LVCMOS33 } [get_ports { LED[9] }]; #IO_L14N_T2_SRCC_14 Sch=led[9]
# set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports { LED[10] }]; #IO_L22P_T3_A05_D21_14 Sch=led[10]
# set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS33 } [get_ports { LED[11] }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=led[11]
# set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { LED[12] }]; #IO_L16P_T2_CSI_B_14 Sch=led[12]
# set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { LED[13] }]; #IO_L22N_T3_A04_D20_14 Sch=led[13]
# set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { LED[14] }]; #IO_L20N_T3_A07_D23_14 Sch=led[14]
# set_property -dict { PACKAGE_PIN V11   IOSTANDARD LVCMOS33 } [get_ports { LED[15] }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]

## RGB LEDs
#set_property -dict { PACKAGE_PIN R12   IOSTANDARD LVCMOS33 } [get_ports { LED16_B }]; #IO_L5P_T0_D06_14 Sch=led16_b
#set_property -dict { PACKAGE_PIN M16   IOSTANDARD LVCMOS33 } [get_ports { LED16_G }]; #IO_L10P_T1_D14_14 Sch=led16_g
#set_property -dict { PACKAGE_PIN N15   IOSTANDARD LVCMOS33 } [get_ports { LED16_R }]; #IO_L11P_T1_SRCC_14 Sch=led16_r
#set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { LED17_B }]; #IO_L15N_T2_DQS_ADV_B_15 Sch=led17_b
#set_property -dict { PACKAGE_PIN R11   IOSTANDARD LVCMOS33 } [get_ports { LED17_G }]; #IO_0_14 Sch=led17_g
#set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports { LED17_R }]; #IO_L11N_T1_SRCC_14 Sch=led17_r

##7 segment display
set_property -dict { PACKAGE_PIN T10   IOSTANDARD LVCMOS33 } [get_ports { CA }]; #IO_L24N_T3_A00_D16_14 Sch=ca
set_property -dict { PACKAGE_PIN R10   IOSTANDARD LVCMOS33 } [get_ports { CB }]; #IO_25_14 Sch=cb
set_property -dict { PACKAGE_PIN K16   IOSTANDARD LVCMOS33 } [get_ports { CC }]; #IO_25_15 Sch=cc
set_property -dict { PACKAGE_PIN K13   IOSTANDARD LVCMOS33 } [get_ports { CD }]; #IO_L17P_T2_A26_15 Sch=cd
set_property -dict { PACKAGE_PIN P15   IOSTANDARD LVCMOS33 } [get_ports { CE }]; #IO_L13P_T2_MRCC_14 Sch=ce
set_property -dict { PACKAGE_PIN T11   IOSTANDARD LVCMOS33 } [get_ports { CF }]; #IO_L19P_T3_A10_D26_14 Sch=cf
set_property -dict { PACKAGE_PIN L18   IOSTANDARD LVCMOS33 } [get_ports { CG }]; #IO_L4P_T0_D04_14 Sch=cg
set_property -dict { PACKAGE_PIN H15   IOSTANDARD LVCMOS33 } [get_ports { DP }]; #IO_L19N_T3_A21_VREF_15 Sch=dp
set_property -dict { PACKAGE_PIN J17   IOSTANDARD LVCMOS33 } [get_ports { AN[0] }]; #IO_L23P_T3_FOE_B_15 Sch=an[0]
set_property -dict { PACKAGE_PIN J18   IOSTANDARD LVCMOS33 } [get_ports { AN[1] }]; #IO_L23N_T3_FWE_B_15 Sch=an[1]
set_property -dict { PACKAGE_PIN T9    IOSTANDARD LVCMOS33 } [get_ports { AN[2] }]; #IO_L24P_T3_A01_D17_14 Sch=an[2]
set_property -dict { PACKAGE_PIN J14   IOSTANDARD LVCMOS33 } [get_ports { AN[3] }]; #IO_L19P_T3_A22_15 Sch=an[3]
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports { AN[4] }]; #IO_L8N_T1_D12_14 Sch=an[4]
set_property -dict { PACKAGE_PIN T14   IOSTANDARD LVCMOS33 } [get_ports { AN[5] }]; #IO_L14P_T2_SRCC_14 Sch=an[5]
set_property -dict { PACKAGE_PIN K2    IOSTANDARD LVCMOS33 } [get_ports { AN[6] }]; #IO_L23P_T3_35 Sch=an[6]
set_property -dict { PACKAGE_PIN U13   IOSTANDARD LVCMOS33 } [get_ports { AN[7] }]; #IO_L23N_T3_A02_D18_14 Sch=an[7]

##CPU Reset Button
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports CPU_RESETN]

##Buttons
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports BTNC]
set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS33 } [get_ports { BTNU }]; #IO_L4N_T0_D05_14 Sch=btnu
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports BTNL]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports BTNR]
#set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports { BTND }]; #IO_L9N_T1_DQS_D13_14 Sch=btnd

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets BTNC_IBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets BTNC]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets BTNC_IBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets BTNL]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets BTNL_IBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets BTNR]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets BTNR_IBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {B[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {B[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {B[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {B[4]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {B[5]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets CLK100MHZ]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets CLK100MHZ_IBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets CLK100MHZ_IBUF_BUFG]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets CPU_RESETN]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets CPU_RESETN_IBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {C[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {C[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {C[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {C[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {C[4]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[4]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[5]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[6]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[7]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[8]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW[9]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[4]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[5]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[6]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[7]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[8]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {SW_IBUF[9]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_B[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_B[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_B[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_B[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_B_OBUF[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_G[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_G[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_G[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_G[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_G_OBUF[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets VGA_HS]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets VGA_HS_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_R[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_R[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_R[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_R[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {VGA_R_OBUF[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets VGA_VS]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets VGA_VS_OBUF]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_100]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_101]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_102]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_103]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_104]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_105]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_106]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_107]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_108]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_109]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_110]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_111]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_112]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_113]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_114]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_115]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_116]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_117]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_118]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_119]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_120]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_121]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_122]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_123]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_124]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_125]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_126]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_127]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_128]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_129]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_130]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_131]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_132]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_133]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_134]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_135]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_136]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_137]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_138]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_139]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_140]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_141]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_142]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_143]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_144]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_145]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_146]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_147]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_148]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_149]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_150]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_151]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_152]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_153]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_154]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_155]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_156]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_157]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_158]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_159]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_160]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_161]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_162]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_163]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_164]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_165]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_166]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_167]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_168]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_169]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_170]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_171]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_172]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_173]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_174]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_175]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_176]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_177]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_178]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_179]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_18]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_180]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_181]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_182]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_183]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_184]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_185]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_186]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_187]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_188]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_189]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_19]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_190]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_191]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_192]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_193]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_194]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_195]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_196]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_197]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_198]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_199]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_20]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_200]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_201]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_202]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_203]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_204]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_205]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_206]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_207]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_208]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_209]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_21]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_210]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_211]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_212]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_213]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_214]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_215]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_216]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_217]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_218]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_219]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_22]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_220]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_221]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_222]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_223]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_224]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_225]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_226]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_227]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_228]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_229]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_23]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_230]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_231]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_232]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_233]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_234]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_235]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_236]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_237]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_238]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_239]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_24]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_240]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_241]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_242]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_243]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_244]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_245]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_246]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_247]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_248]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_249]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_25]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_250]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_251]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_252]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_253]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_254]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_255]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_256]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_257]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_258]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_259]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_26]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_260]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_261]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_262]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_263]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_264]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_265]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_266]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_267]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_268]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_269]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_27]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_270]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_271]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_272]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_273]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_274]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_275]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_276]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_277]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_278]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_279]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_28]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_280]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_281]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_282]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_283]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_284]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_285]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_286]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_287]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_288]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_289]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_29]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_290]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_291]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_292]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_293]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_294]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_295]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_296]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_297]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_298]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_299]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_30]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_300]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_301]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_302]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_303]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_304]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_305]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_306]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_307]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_308]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_309]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_31]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_310]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_311]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_312]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_313]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_314]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_315]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_316]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_317]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_318]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_319]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_32]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_326]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_327]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_328]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_329]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_33]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_330]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_331]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_332]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_333]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_334]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_335]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_336]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_337]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_338]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_339]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_34]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_340]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_341]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_342]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_343]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_344]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_345]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_346]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_347]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_35]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_36]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_37]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_38]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_39]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_40]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_41]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_42]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_43]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_44]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_45]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_46]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_47]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_48]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_49]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_50]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_51]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_52]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_53]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_54]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_55]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_56]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_57]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_58]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_59]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_60]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_61]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_62]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_63]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_64]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_65]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_66]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_67]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_68]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_69]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_70]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_71]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_72]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_73]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_74]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_75]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_76]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_77]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_78]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_79]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_80]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_81]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_82]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_83]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_84]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_85]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_86]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_87]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_88]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_89]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_90]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_91]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_92]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_93]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_94]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_95]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_96]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_97]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_98]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets cicrle_datapath_n_99]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets circle_ff]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets clear_ff]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets clear_press_n_1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {color_out[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {color_out[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {color_out[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_17]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_19]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_22]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_23]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_24]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_25]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_26]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_27]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_28]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_29]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_30]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_31]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_32]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_33]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_34]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_35]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_36]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_37]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_38]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_39]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_40]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_41]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_42]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_43]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_44]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_45]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_46]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_51]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_52]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_53]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_54]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_55]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_56]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_57]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_58]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_59]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_60]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_61]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_62]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_63]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_64]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_65]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_66]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_67]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets controlpath_inst_n_68]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_10]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_11]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_12]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_13]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_14]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_15]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_16]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_17]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_18]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_19]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_20]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_21]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_22]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_23]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_24]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_25]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_26]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_27]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_28]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_29]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_30]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_31]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_32]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_33]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_34]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_35]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_36]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_37]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets core_inst_n_9]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {current_state[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {current_state[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {current_state[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets enC_ff]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets enY]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets line_ff]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets lineclear_datapath_n_15]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets lineclear_datapath_n_16]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {p_0_in[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {p_0_in[4]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets plot]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {reg_d3[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {reg_d3[4]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {reg_d[9]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets reg_yB]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {reg_yB_reg[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets reset0]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {sel0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {sel0[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {sel0[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address1[6]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address1[7]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address1[8]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address1[9]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[10]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[11]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[12]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[13]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[14]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[6]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[7]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[8]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {write_address[9]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets xB_yB_comp0]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets x_count_reset]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {x_line[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {x_line[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {x_line[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {x_line[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {x_line[4]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {x_line[5]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {x_line[6]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {x_line[7]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {y_line[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {y_line[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {y_line[2]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {y_line__0[3]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {y_line__0[4]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {y_line__0[5]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {y_line__0[6]}]

##Pmod Headers
##Pmod Header JA
#set_property -dict { PACKAGE_PIN C17   IOSTANDARD LVCMOS33 } [get_ports { JA[1] }]; #IO_L20N_T3_A19_15 Sch=ja[1]
#set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { JA[2] }]; #IO_L21N_T3_DQS_A18_15 Sch=ja[2]
#set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports { JA[3] }]; #IO_L21P_T3_DQS_15 Sch=ja[3]
#set_property -dict { PACKAGE_PIN G17   IOSTANDARD LVCMOS33 } [get_ports { JA[4] }]; #IO_L18N_T2_A23_15 Sch=ja[4]
#set_property -dict { PACKAGE_PIN D17   IOSTANDARD LVCMOS33 } [get_ports { JA[7] }]; #IO_L16N_T2_A27_15 Sch=ja[7]
#set_property -dict { PACKAGE_PIN E17   IOSTANDARD LVCMOS33 } [get_ports { JA[8] }]; #IO_L16P_T2_A28_15 Sch=ja[8]
#set_property -dict { PACKAGE_PIN F18   IOSTANDARD LVCMOS33 } [get_ports { JA[9] }]; #IO_L22N_T3_A16_15 Sch=ja[9]
#set_property -dict { PACKAGE_PIN G18   IOSTANDARD LVCMOS33 } [get_ports { JA[10] }]; #IO_L22P_T3_A17_15 Sch=ja[10]

##Pmod Header JB
#set_property -dict { PACKAGE_PIN D14   IOSTANDARD LVCMOS33 } [get_ports { JB[1] }]; #IO_L1P_T0_AD0P_15 Sch=jb[1]
#set_property -dict { PACKAGE_PIN F16   IOSTANDARD LVCMOS33 } [get_ports { JB[2] }]; #IO_L14N_T2_SRCC_15 Sch=jb[2]
#set_property -dict { PACKAGE_PIN G16   IOSTANDARD LVCMOS33 } [get_ports { JB[3] }]; #IO_L13N_T2_MRCC_15 Sch=jb[3]
#set_property -dict { PACKAGE_PIN H14   IOSTANDARD LVCMOS33 } [get_ports { JB[4] }]; #IO_L15P_T2_DQS_15 Sch=jb[4]
#set_property -dict { PACKAGE_PIN E16   IOSTANDARD LVCMOS33 } [get_ports { JB[7] }]; #IO_L11N_T1_SRCC_15 Sch=jb[7]
#set_property -dict { PACKAGE_PIN F13   IOSTANDARD LVCMOS33 } [get_ports { JB[8] }]; #IO_L5P_T0_AD9P_15 Sch=jb[8]
#set_property -dict { PACKAGE_PIN G13   IOSTANDARD LVCMOS33 } [get_ports { JB[9] }]; #IO_0_15 Sch=jb[9]
#set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { JB[10] }]; #IO_L13P_T2_MRCC_15 Sch=jb[10]

##Pmod Header JC
#set_property -dict { PACKAGE_PIN K1    IOSTANDARD LVCMOS33 } [get_ports { JC[1] }]; #IO_L23N_T3_35 Sch=jc[1]
#set_property -dict { PACKAGE_PIN F6    IOSTANDARD LVCMOS33 } [get_ports { JC[2] }]; #IO_L19N_T3_VREF_35 Sch=jc[2]
#set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports { JC[3] }]; #IO_L22N_T3_35 Sch=jc[3]
#set_property -dict { PACKAGE_PIN G6    IOSTANDARD LVCMOS33 } [get_ports { JC[4] }]; #IO_L19P_T3_35 Sch=jc[4]
#set_property -dict { PACKAGE_PIN E7    IOSTANDARD LVCMOS33 } [get_ports { JC[7] }]; #IO_L6P_T0_35 Sch=jc[7]
#set_property -dict { PACKAGE_PIN J3    IOSTANDARD LVCMOS33 } [get_ports { JC[8] }]; #IO_L22P_T3_35 Sch=jc[8]
#set_property -dict { PACKAGE_PIN J4    IOSTANDARD LVCMOS33 } [get_ports { JC[9] }]; #IO_L21P_T3_DQS_35 Sch=jc[9]
#set_property -dict { PACKAGE_PIN E6    IOSTANDARD LVCMOS33 } [get_ports { JC[10] }]; #IO_L5P_T0_AD13P_35 Sch=jc[10]

##Pmod Header JD
#set_property -dict { PACKAGE_PIN H4    IOSTANDARD LVCMOS33 } [get_ports { JD[1] }]; #IO_L21N_T3_DQS_35 Sch=jd[1]
#set_property -dict { PACKAGE_PIN H1    IOSTANDARD LVCMOS33 } [get_ports { JD[2] }]; #IO_L17P_T2_35 Sch=jd[2]
#set_property -dict { PACKAGE_PIN G1    IOSTANDARD LVCMOS33 } [get_ports { JD[3] }]; #IO_L17N_T2_35 Sch=jd[3]
#set_property -dict { PACKAGE_PIN G3    IOSTANDARD LVCMOS33 } [get_ports { JD[4] }]; #IO_L20N_T3_35 Sch=jd[4]
#set_property -dict { PACKAGE_PIN H2    IOSTANDARD LVCMOS33 } [get_ports { JD[7] }]; #IO_L15P_T2_DQS_35 Sch=jd[7]
#set_property -dict { PACKAGE_PIN G4    IOSTANDARD LVCMOS33 } [get_ports { JD[8] }]; #IO_L20P_T3_35 Sch=jd[8]
#set_property -dict { PACKAGE_PIN G2    IOSTANDARD LVCMOS33 } [get_ports { JD[9] }]; #IO_L15N_T2_DQS_35 Sch=jd[9]
#set_property -dict { PACKAGE_PIN F3    IOSTANDARD LVCMOS33 } [get_ports { JD[10] }]; #IO_L13N_T2_MRCC_35 Sch=jd[10]

##Pmod Header JXADC
#set_property -dict { PACKAGE_PIN A14   IOSTANDARD LVCMOS33 } [get_ports { XA_N[1] }]; #IO_L9N_T1_DQS_AD3N_15 Sch=xa_n[1]
#set_property -dict { PACKAGE_PIN A13   IOSTANDARD LVCMOS33 } [get_ports { XA_P[1] }]; #IO_L9P_T1_DQS_AD3P_15 Sch=xa_p[1]
#set_property -dict { PACKAGE_PIN A16   IOSTANDARD LVCMOS33 } [get_ports { XA_N[2] }]; #IO_L8N_T1_AD10N_15 Sch=xa_n[2]
#set_property -dict { PACKAGE_PIN A15   IOSTANDARD LVCMOS33 } [get_ports { XA_P[2] }]; #IO_L8P_T1_AD10P_15 Sch=xa_p[2]
#set_property -dict { PACKAGE_PIN B17   IOSTANDARD LVCMOS33 } [get_ports { XA_N[3] }]; #IO_L7N_T1_AD2N_15 Sch=xa_n[3]
#set_property -dict { PACKAGE_PIN B16   IOSTANDARD LVCMOS33 } [get_ports { XA_P[3] }]; #IO_L7P_T1_AD2P_15 Sch=xa_p[3]
#set_property -dict { PACKAGE_PIN A18   IOSTANDARD LVCMOS33 } [get_ports { XA_N[4] }]; #IO_L10N_T1_AD11N_15 Sch=xa_n[4]
#set_property -dict { PACKAGE_PIN B18   IOSTANDARD LVCMOS33 } [get_ports { XA_P[4] }]; #IO_L10P_T1_AD11P_15 Sch=xa_p[4]

#VGA Connector
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {VGA_R[0]}]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {VGA_R[1]}]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {VGA_R[2]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {VGA_R[3]}]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[0]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {VGA_G[1]}]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[2]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[3]}]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[0]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[1]}]
set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[2]}]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {VGA_B[3]}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports VGA_HS]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports VGA_VS]

##Micro SD Connector
#set_property -dict { PACKAGE_PIN E2    IOSTANDARD LVCMOS33 } [get_ports { SD_RESET }]; #IO_L14P_T2_SRCC_35 Sch=sd_reset
#set_property -dict { PACKAGE_PIN A1    IOSTANDARD LVCMOS33 } [get_ports { SD_CD }]; #IO_L9N_T1_DQS_AD7N_35 Sch=sd_cd
#set_property -dict { PACKAGE_PIN B1    IOSTANDARD LVCMOS33 } [get_ports { SD_SCK }]; #IO_L9P_T1_DQS_AD7P_35 Sch=sd_sck
#set_property -dict { PACKAGE_PIN C1    IOSTANDARD LVCMOS33 } [get_ports { SD_CMD }]; #IO_L16N_T2_35 Sch=sd_cmd
#set_property -dict { PACKAGE_PIN C2    IOSTANDARD LVCMOS33 } [get_ports { SD_DAT[0] }]; #IO_L16P_T2_35 Sch=sd_dat[0]
#set_property -dict { PACKAGE_PIN E1    IOSTANDARD LVCMOS33 } [get_ports { SD_DAT[1] }]; #IO_L18N_T2_35 Sch=sd_dat[1]
#set_property -dict { PACKAGE_PIN F1    IOSTANDARD LVCMOS33 } [get_ports { SD_DAT[2] }]; #IO_L18P_T2_35 Sch=sd_dat[2]
#set_property -dict { PACKAGE_PIN D2    IOSTANDARD LVCMOS33 } [get_ports { SD_DAT[3] }]; #IO_L14N_T2_SRCC_35 Sch=sd_dat[3]

##Accelerometer
#set_property -dict { PACKAGE_PIN E15   IOSTANDARD LVCMOS33 } [get_ports { ACL_MISO }]; #IO_L11P_T1_SRCC_15 Sch=acl_miso
#set_property -dict { PACKAGE_PIN F14   IOSTANDARD LVCMOS33 } [get_ports { ACL_MOSI }]; #IO_L5N_T0_AD9N_15 Sch=acl_mosi
#set_property -dict { PACKAGE_PIN F15   IOSTANDARD LVCMOS33 } [get_ports { ACL_SCLK }]; #IO_L14P_T2_SRCC_15 Sch=acl_sclk
#set_property -dict { PACKAGE_PIN D15   IOSTANDARD LVCMOS33 } [get_ports { ACL_CSN }]; #IO_L12P_T1_MRCC_15 Sch=acl_csn
#set_property -dict { PACKAGE_PIN B13   IOSTANDARD LVCMOS33 } [get_ports { ACL_INT[1] }]; #IO_L2P_T0_AD8P_15 Sch=acl_int[1]
#set_property -dict { PACKAGE_PIN C16   IOSTANDARD LVCMOS33 } [get_ports { ACL_INT[2] }]; #IO_L20P_T3_A20_15 Sch=acl_int[2]

##Temperature Sensor
#set_property -dict { PACKAGE_PIN C14   IOSTANDARD LVCMOS33 } [get_ports { TMP_SCL }]; #IO_L1N_T0_AD0N_15 Sch=tmp_scl
#set_property -dict { PACKAGE_PIN C15   IOSTANDARD LVCMOS33 } [get_ports { TMP_SDA }]; #IO_L12N_T1_MRCC_15 Sch=tmp_sda
#set_property -dict { PACKAGE_PIN D13   IOSTANDARD LVCMOS33 } [get_ports { TMP_INT }]; #IO_L6N_T0_VREF_15 Sch=tmp_int
#set_property -dict { PACKAGE_PIN B14   IOSTANDARD LVCMOS33 } [get_ports { TMP_CT }]; #IO_L2N_T0_AD8N_15 Sch=tmp_ct

##Omnidirectional Microphone
#set_property -dict { PACKAGE_PIN J5    IOSTANDARD LVCMOS33 } [get_ports { M_CLK }]; #IO_25_35 Sch=m_clk
#set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { M_DATA }]; #IO_L24N_T3_35 Sch=m_data
#set_property -dict { PACKAGE_PIN F5    IOSTANDARD LVCMOS33 } [get_ports { M_LRSEL }]; #IO_0_35 Sch=m_lrsel

##PWM Audio Amplifier
#set_property -dict { PACKAGE_PIN A11   IOSTANDARD LVCMOS33 } [get_ports { AUD_PWM }]; #IO_L4N_T0_15 Sch=aud_pwm
#set_property -dict { PACKAGE_PIN D12   IOSTANDARD LVCMOS33 } [get_ports { AUD_SD }]; #IO_L6P_T0_15 Sch=aud_sd

##USB-RS232 Interface
#set_property -dict { PACKAGE_PIN C4    IOSTANDARD LVCMOS33 } [get_ports { UART_TXD_IN }]; #IO_L7P_T1_AD6P_35 Sch=uart_txd_in
#set_property -dict { PACKAGE_PIN D4    IOSTANDARD LVCMOS33 } [get_ports { UART_RXD_OUT }]; #IO_L11N_T1_SRCC_35 Sch=uart_rxd_out
#set_property -dict { PACKAGE_PIN D3    IOSTANDARD LVCMOS33 } [get_ports { UART_CTS }]; #IO_L12N_T1_MRCC_35 Sch=uart_cts
#set_property -dict { PACKAGE_PIN E5    IOSTANDARD LVCMOS33 } [get_ports { UART_RTS }]; #IO_L5N_T0_AD13N_35 Sch=uart_rts

##USB HID (PS/2)
#set_property -dict { PACKAGE_PIN F4    IOSTANDARD LVCMOS33 } [get_ports { PS2_CLK }]; #IO_L13P_T2_MRCC_35 Sch=ps2_clk
#set_property -dict { PACKAGE_PIN B2    IOSTANDARD LVCMOS33 } [get_ports { PS2_DATA }]; #IO_L10N_T1_AD15N_35 Sch=ps2_data

##SMSC Ethernet PHY
#set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { ETH_MDC }]; #IO_L11P_T1_SRCC_16 Sch=eth_mdc
#set_property -dict { PACKAGE_PIN A9    IOSTANDARD LVCMOS33 } [get_ports { ETH_MDIO }]; #IO_L14N_T2_SRCC_16 Sch=eth_mdio
#set_property -dict { PACKAGE_PIN B3    IOSTANDARD LVCMOS33 } [get_ports { ETH_RSTN }]; #IO_L10P_T1_AD15P_35 Sch=eth_rstn
#set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { ETH_CRSDV }]; #IO_L6N_T0_VREF_16 Sch=eth_crsdv
#set_property -dict { PACKAGE_PIN C10   IOSTANDARD LVCMOS33 } [get_ports { ETH_RXERR }]; #IO_L13N_T2_MRCC_16 Sch=eth_rxerr
#set_property -dict { PACKAGE_PIN C11   IOSTANDARD LVCMOS33 } [get_ports { ETH_RXD[0] }]; #IO_L13P_T2_MRCC_16 Sch=eth_rxd[0]
#set_property -dict { PACKAGE_PIN D10   IOSTANDARD LVCMOS33 } [get_ports { ETH_RXD[1] }]; #IO_L19N_T3_VREF_16 Sch=eth_rxd[1]
#set_property -dict { PACKAGE_PIN B9    IOSTANDARD LVCMOS33 } [get_ports { ETH_TXEN }]; #IO_L11N_T1_SRCC_16 Sch=eth_txen
#set_property -dict { PACKAGE_PIN A10   IOSTANDARD LVCMOS33 } [get_ports { ETH_TXD[0] }]; #IO_L14P_T2_SRCC_16 Sch=eth_txd[0]
#set_property -dict { PACKAGE_PIN A8    IOSTANDARD LVCMOS33 } [get_ports { ETH_TXD[1] }]; #IO_L12N_T1_MRCC_16 Sch=eth_txd[1]
#set_property -dict { PACKAGE_PIN D5    IOSTANDARD LVCMOS33 } [get_ports { ETH_REFCLK }]; #IO_L11P_T1_SRCC_35 Sch=eth_refclk
#set_property -dict { PACKAGE_PIN B8    IOSTANDARD LVCMOS33 } [get_ports { ETH_INTN }]; #IO_L12P_T1_MRCC_16 Sch=eth_intn

##Quad SPI Flash
#set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports { QSPI_DQ[0] }]; #IO_L1P_T0_D00_MOSI_14 Sch=qspi_dq[0]
#set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { QSPI_DQ[1] }]; #IO_L1N_T0_D01_DIN_14 Sch=qspi_dq[1]
#set_property -dict { PACKAGE_PIN L14   IOSTANDARD LVCMOS33 } [get_ports { QSPI_DQ[2] }]; #IO_L2P_T0_D02_14 Sch=qspi_dq[2]
#set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { QSPI_DQ[3] }]; #IO_L2N_T0_D03_14 Sch=qspi_dq[3]
#set_property -dict { PACKAGE_PIN L13   IOSTANDARD LVCMOS33 } [get_ports { QSPI_CSN }]; #IO_L6P_T0_FCS_B_14 Sch=qspi_csn

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK100MHZ_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {current_state[0]} {current_state[1]} {current_state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {x_line[0]} {x_line[1]} {x_line[2]} {x_line[3]} {x_line[4]} {x_line[5]} {x_line[6]} {x_line[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {y_line[0]} {y_line[1]} {y_line[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {y_line__0[3]} {y_line__0[4]} {y_line__0[5]} {y_line__0[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 3 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {controlpath_inst/next_state[0]} {controlpath_inst/next_state[1]} {controlpath_inst/next_state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list controlpath_inst/BTNC_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list controlpath_inst/BTNL_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list controlpath_inst/BTNR_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list CLK100MHZ_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list plot]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list xB_yB_comp0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list lineclear_datapath/enY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list lineclear_datapath/x_count_reset]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK100MHZ_IBUF_BUFG]
