#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Dec 09 17:26:33 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 90ade408325743189163f653a599d5ab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot tb_VGA_TOP_func_synth xil_defaultlib.tb_VGA_TOP xil_defaultlib.glbl -log elaborate.log"
xelab -wto 90ade408325743189163f653a599d5ab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot tb_VGA_TOP_func_synth xil_defaultlib.tb_VGA_TOP xil_defaultlib.glbl -log elaborate.log

