#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 09 16:33:16 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_VGA_TOP_behav -key {Behavioral:sim_1:Functional:tb_VGA_TOP} -tclbatch tb_VGA_TOP.tcl -view /home/it/DigitalSystemDesign/Assignment2/VGA_top/tb_VGA_TOP_behav.wcfg -log simulate.log"
xsim tb_VGA_TOP_behav -key {Behavioral:sim_1:Functional:tb_VGA_TOP} -tclbatch tb_VGA_TOP.tcl -view /home/it/DigitalSystemDesign/Assignment2/VGA_top/tb_VGA_TOP_behav.wcfg -log simulate.log

