# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 5
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.cache/wt [current_project]
set_property parent.project_path /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/imports/it/DigitalSystemDesign/Assignment2/VGA_display_top/VGA_display_top.srcs/sources_1/imports/data_path/bresenham_algo/bresenham_algo.srcs/sources_1/new/bresenham_algo.sv
  /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/imports/it/DigitalSystemDesign/Assignment2/VGA_display_top/VGA_display_top.srcs/sources_1/imports/controlpath/controlpath.srcs/sources_1/new/controlpath.sv
  /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/imports/it/DigitalSystemDesign/Assignment2/VGA_display_top/VGA_display_top.srcs/sources_1/imports/data_path/bresenham_algo/bresenham_algo.srcs/sources_1/imports/Lab4/d_FF/d_FF_srcs/d_flipflop.sv
  /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/imports/it/DigitalSystemDesign/Assignment2/VGA_display_top/VGA_display_top.srcs/sources_1/imports/data_path/line_clear/line_clear.srcs/sources_1/new/lineclear_algo.sv
  /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/imports/it/DigitalSystemDesign/Assignment2/VGA_display_top/VGA_display_top.srcs/sources_1/imports/data_path/bresenham_algo/bresenham_algo.srcs/sources_1/imports/new/nbit_counter.sv
  /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/imports/Downloads/vga_core.sv
  /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/imports/Downloads/video_memory.sv
  /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/new/VGA_TOP.sv
}
read_verilog -library xil_defaultlib /home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/sources_1/imports/Downloads/vga_controller.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/constrs_1/imports/FPGA programming files/pin-assignment.xdc}}
set_property used_in_implementation false [get_files {{/home/it/DigitalSystemDesign/Assignment2/VGA_top/VGA_top.srcs/constrs_1/imports/FPGA programming files/pin-assignment.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top VGA_TOP -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef VGA_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file VGA_TOP_utilization_synth.rpt -pb VGA_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
